// Code generated by tygo. DO NOT EDIT.

//////////
// source: any.go
/*
Example for https://github.com/nasoooor29/tygo/issues/65
*/

export interface AnyStructField<T extends any> {
  Value: T;
  SomeField: string;
}
export type JsonArray<T extends any> = T[];
